cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'git'
brew 'nvm'
brew 'python'
brew 'scala'
brew 'maven31'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'vim'
brew 'go'
brew 'grc'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'unrar'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'ffmpeg'
brew 'hub'

cask 'java8'
cask 'atom'
cask 'google-chrome'
cask 'slack'
cask 'tunnelbear'
cask 'intellij-idea'
cask 'spotify'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'alfred'
cask 'docker'
cask 'dropbox'
cask 'fantastical'
cask 'yemuzip'
cask 'macdown'
cask 'iterm2'
cask 'adobe-creative-cloud'
cask 'touchswitcher'
cask 'dashlane'
case 'Karabiner'

# Quick look plugins - https://github.com/sindresorhus/quick-look-plugins
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'qlprettypatch'
cask 'qlstephen'
